on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies and build
        run: |
          cd frontend
          echo "REACT_APP_GIPHY_API_KEY=${{ secrets.REACT_APP_GIPHY_API_KEY }}" >> .env
          echo "GENERATE_SOURCEMAP=${{ secrets.GENERATE_SOURCEMAP }}" >> .env
          npm install
          npm run build

      - name: Clean up existing files on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USER }}
          port: ${{ secrets.API_PORT }}
          password: ${{ secrets.API_PASSWORD }}
          script: |
            rm -rf /home/codeclash/frontend
            
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USER }}
          port: ${{ secrets.API_PORT }}
          password: ${{ secrets.API_PASSWORD }}
          source: frontend/build
          target: /home/codeclash
